alter table business_settings
  add column if not exists primary_phone text,
  add column if not exists primary_email text,
  add column if not exists website_url text,
  add column if not exists company_logo_url text,
  add column if not exists ellsworth_address text,
  add column if not exists ellsworth_phone text,
  add column if not exists ellsworth_email text,
  add column if not exists lindsay_address text,
  add column if not exists lindsay_phone text,
  add column if not exists lindsay_email text,
  add column if not exists quote_logo_position text default 'left',
  add column if not exists quote_show_company_name boolean default true,
  add column if not exists quote_show_address boolean default true,
  add column if not exists quote_address_mode text default 'both',
  add column if not exists quote_show_tagline boolean default false,
  add column if not exists quote_tagline text,
  add column if not exists secondary_color text default '#1C1C1C',
  add column if not exists quote_footer_text text,
  add column if not exists payment_terms_text text default '50% deposit due at signing. Balance due upon completion of installation.',
  add column if not exists quote_show_payment_terms boolean default true,
  add column if not exists quote_show_room_label boolean default true,
  add column if not exists quote_show_product_name boolean default true,
  add column if not exists quote_show_fabric_color boolean default true,
  add column if not exists quote_show_lift_option boolean default true,
  add column if not exists quote_show_measurements boolean default false,
  add column if not exists quote_show_quantity boolean default true,
  add column if not exists quote_show_unit_price boolean default true,
  add column if not exists quote_show_line_total boolean default true,
  add column if not exists quote_show_subtotal boolean default true,
  add column if not exists quote_show_tax boolean default true,
  add column if not exists quote_show_shipping boolean default false,
  add column if not exists quote_show_installation boolean default false,
  add column if not exists disclaimer_text text,
  add column if not exists quote_email_subject text,
  add column if not exists quote_email_body text,
  add column if not exists appointment_email_subject text,
  add column if not exists appointment_email_body text,
  add column if not exists install_email_subject text,
  add column if not exists install_email_body text,
  add column if not exists install_on_my_way_sms text,
  add column if not exists deposit_percentage numeric default 50,
  add column if not exists ellsworth_tax_rate numeric default 0.0875,
  add column if not exists lindsay_tax_rate numeric default 0.0875;

create table if not exists shipping_rules (
  id uuid primary key default gen_random_uuid(),
  manufacturer_id uuid references manufacturers(id) on delete cascade,
  rule_type text not null default 'Flat rate',
  amount numeric default 0,
  created_at timestamptz default now()
);
